<Project>
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <VersionPrefix>0.1.13</VersionPrefix>
    <Product>CyRevision</Product>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <NuGetAudit Condition="'$(CI)' != 'true'">false</NuGetAudit>
  </PropertyGroup>
</Project>
