#pragma once

#include "Runtime/Launch/Resources/Version.h"

#define CYREVISION_UE4 (ENGINE_MAJOR_VERSION < 5)
#define CYREVISION_UE5 (ENGINE_MAJOR_VERSION >= 5)
#define CYREVISION_UE_VERSION_AT_LEAST(Major, Minor) \
    ((ENGINE_MAJOR_VERSION > (Major)) || (ENGINE_MAJOR_VERSION == (Major) && ENGINE_MINOR_VERSION >= (Minor)))
#define CYREVISION_UE_VERSION_BEFORE(Major, Minor) \
    ((ENGINE_MAJOR_VERSION < (Major)) || (ENGINE_MAJOR_VERSION == (Major) && ENGINE_MINOR_VERSION < (Minor)))

#define CYREVISION_UE5_3_OR_LATER CYREVISION_UE_VERSION_AT_LEAST(5, 3)
#define CYREVISION_UE5_7_OR_LATER CYREVISION_UE_VERSION_AT_LEAST(5, 7)
#define CYREVISION_UE5_8_OR_LATER CYREVISION_UE_VERSION_AT_LEAST(5, 8)
