<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CyRevision.Core\CyRevision.Core.csproj" />
    <ProjectReference Include="..\CyRevision.Security\CyRevision.Security.csproj" />
  </ItemGroup>
</Project>
