<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>CyRevision.Plugin.Godot</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CyRevision.Plugin.Abstractions\CyRevision.Plugin.Abstractions.csproj" />
  </ItemGroup>
</Project>
